# Generated by Django 5.0.7 on 2024-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to='teachers/')),
                ('description', models.TextField()),
                ('specialty', models.CharField(max_length=100)),
                ('comment', models.ManyToManyField(to='courses.comment')),
                ('courses', models.ManyToManyField(to='courses.course')),
            ],
        ),
    ]
