# Generated by Django 5.0.7 on 2024-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0002_specialty_alter_teacher_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
