# Generated by Django 5.0.7 on 2024-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0003_alter_teacher_specialty_alter_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='comment',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teacher', to='courses.course'),
        ),
    ]
