# Generated by Django 5.0.7 on 2024-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0004_remove_teacher_comment_alter_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', to='teachers.teacher'),
        ),
    ]
