# Generated by Django 5.0.7 on 2024-07-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_teachers'),
        ('teachers', '0005_remove_teacher_address_remove_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers.teacher'),
            preserve_default=False,
        ),
    ]
