# Generated by Django 5.0.7 on 2024-07-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='join_date',
        ),
    ]
